/* PROJECT: Private High School Advancement - 00_Infrastructure
   PURPOSE: Create 'donors' table with exact 112-column mapping.
   GOVERNANCE: Resolves duplicate columns and 'engagement_score' naming conflict. Adds correct name to standardized engagement score. 
*/

DROP TABLE IF EXISTS donors;

CREATE TABLE donors (
    ID INTEGER PRIMARY KEY,
    First_Name TEXT,
    Last_Name TEXT,
    Full_Name TEXT,
    Gender TEXT,
    donor_type TEXT,
    Constituent_Type_2 TEXT,
    Class_Year TEXT,
    Parent_Year TEXT,
    Primary_Manager TEXT,
    Rating TEXT,
    Prospect_Stage TEXT,
    Lifetime_Giving REAL,
    Last_Gift REAL,
    Last_Gift_Designation TEXT,
    Last_Gift_Date TEXT,
    Consecutive_Yr_Giving_Count INTEGER,
    Total_Yr_Giving_Count INTEGER,
    Rating_Giving_Alignment TEXT,
    Family_ID TEXT,
    Relationship_Type TEXT,
    Family_Giving_Potential TEXT,
    region TEXT,
    Professional_Background TEXT,
    Interest_Keywords TEXT,
    Engagement_Score REAL,           -- First occurrence (Raw)
    Legacy_Intent_Probability REAL,
    Legacy_Intent_Binary INTEGER,
    Board_Affiliations TEXT,
    Estimated_Age REAL,
    total_relationships REAL,
    outgoing_relationships REAL,
    incoming_relationships REAL,
    relationship_diversity REAL,
    avg_relationship_strength REAL,
    max_relationship_strength REAL,
    professional_network_size REAL,
    social_network_size REAL,
    alumni_network_size REAL,
    family_network_size REAL,
    philanthropic_network_size REAL,
    geographic_network_size REAL,
    network_avg_giving REAL,
    network_max_giving REAL,
    network_total_giving REAL,
    high_value_connections REAL,
    "index" TEXT,
    gifts_per_year REAL,
    gift_frequency REAL,
    last_gift_amount REAL,
    frequency_score REAL,
    gift_count REAL,
    giving_years REAL,
    total_gifts REAL,
    years_active REAL,
    consecutive_years REAL,
    recency_score REAL,
    running_avg_last_3 REAL,
    days_since_last_gift REAL,
    rfm_score REAL,
    time_weighted_giving REAL,
    is_multi_year INTEGER,
    gift_frequency_variability REAL,
    giving_velocity REAL,
    years_since_first_gift REAL,
    monetary_score REAL,
    is_loyal_donor INTEGER,
    gave_in_24mo INTEGER,
    gifts_last_24mo REAL,
    gift_consistency REAL,
    avg_gift_amount REAL,
    avg_gift_size REAL,
    total_lifetime_giving REAL,
    total_amount REAL,
    giving_consistency REAL,
    engagement_score_standardized REAL, -- Renamed duplicate for integrity
    gifts_last_12mo REAL,
    gave_in_12mo INTEGER,
    years_inactive REAL,
    recent_giving_amount REAL,
    recently_engaged INTEGER,
    gave_in_6mo INTEGER,
    gifts_last_6mo REAL,
    engagement_giving_interaction REAL,
    giving_momentum REAL,
    other_region INTEGER,
    is_recent_donor INTEGER,
    senior_age INTEGER,
    young_age INTEGER,
    medium_capacity_industry INTEGER,
    high_capacity_industry INTEGER,
    qualified_rating INTEGER,
    wealthy_region INTEGER,
    other_industry INTEGER,
    mid_career_age INTEGER,
    net_giving_interaction REAL,
    pagerank REAL,
    has_network INTEGER,
    has_board_role INTEGER,
    community_id REAL,
    community_size REAL,
    role_giving_interaction REAL,
    Gave_Again_In_2024 INTEGER,
    Gave_Again_In_2025 INTEGER,
    high_rating INTEGER,
    network_size REAL,
    degree_centrality REAL,
    influence_score REAL,
    high_influence_role INTEGER,
    clustering_coefficient REAL,
    has_estate_capacity INTEGER,
    Will_Give_Again_Probability REAL
);